issue ClassCastException: jnr.posix.WindowsFileStat cannot be cast
Was receiving the following

```
java.lang.ClassCastException: jnr.posix.WindowsFileStat cannot be cast
to jnr.posix.WindowsRawFileStat
        at jnr.posix.WindowsPOSIX.fstat(WindowsPOSIX.java:337)
        at jnr.posix.WindowsPOSIX.fstat(WindowsPOSIX.java:329)
        at jnr.posix.WindowsPOSIX.fstat(WindowsPOSIX.java:322)
        at jnr.posix.CheckedPOSIX.fstat(CheckedPOSIX.java:125)
        at jnr.posix.LazyPOSIX.fstat(LazyPOSIX.java:122)
        at jnr.posix.FileStatTest.filestatInt(FileStatTest.java:133)
```

change it using `WindowsRawFileStat` which was being expected